[package]
name = "zed_liquid"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

# [lints]
# workspace = true

[lib]
path = "src/liquid.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"
