id = "liquid"
name = "Liquid"
version = "0.1.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/TheBeyondGroup/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/hankthetank27/tree-sitter-liquid"
commit = "23ac814111e2b4b4b083e2c92219af2d5b74d13d"

[language_servers.liquid]
name = "Liquid LSP"
languages = ["Liquid"]
