id = "liquid"
name = "Liquid"
version = "0.5.1"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/TheBeyondGroup/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/hankthetank27/tree-sitter-liquid"
commit = "9566ca79911052919fce09d26f1f655b5e093857"

[language_servers.liquid]
name = "Liquid LSP"
languages = ["Liquid"]
