id = "liquid"
name = "Liquid"
version = "0.6.2"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/TheBeyondGroup/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/RomainDW/tree-sitter-liquid-1"
commit = "a88667733beca52f5ff3db69c08f033a2a9318c3"

[language_servers.liquid]
name = "Liquid LSP"
languages = ["Liquid"]
