id = "liquid"
name = "Liquid"
version = "0.2.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/TheBeyondGroup/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/hankthetank27/tree-sitter-liquid"
commit = "d68a255c393cfefa9d3185023e2f1684a52907ed"

[language_servers.liquid]
name = "Liquid LSP"
languages = ["Liquid"]
