id = "liquid"
name = "Liquid"
version = "0.7.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/TheBeyondGroup/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/hankthetank27/tree-sitter-liquid"
commit = "e45dbac8c5fa95b1f0e00e7e0c04bc8855823391"

[language_servers.liquid]
name = "Liquid LSP"
languages = ["Liquid"]
